import { supabase } from './supabase';

const WIDGET_ID_KEY = 'overlay_widget_id';

export function getWidgetId() {
  let id = localStorage.getItem(WIDGET_ID_KEY);
  if (!id) {
    id = Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
    localStorage.setItem(WIDGET_ID_KEY, id);
  }
  return id;
}

// Convert base64 to Blob
async function base64ToBlob(base64Url) {
  const res = await fetch(base64Url);
  return res.blob();
}

/**
 * Uploads base64 media to Supabase Storage and returns the public URL.
 * If the url is already a Supabase public URL, just returns it.
 */
async function uploadMedia(userId, base64Url, fileName) {
  if (!base64Url || base64Url.startsWith('http')) return base64Url;

  const blob = await base64ToBlob(base64Url);
  const ext = fileName.split('.').pop() || 'png';
  const filePath = `${userId}/${Date.now()}_${Math.random().toString(36).substring(7)}.${ext}`;

  const { data, error } = await supabase.storage
    .from('media')
    .upload(filePath, blob, { upsert: false });

  if (error) {
    console.error('Upload Error:', error);
    throw error;
  }

  const { data: publicData } = supabase.storage.from('media').getPublicUrl(filePath);
  return publicData.publicUrl;
}

export async function loadMediaConfigs() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];

  const { data, error } = await supabase
    .from('media_configs')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Fetch Configs Error:', error);
    return [];
  }

  return data.map(row => ({ id: row.id, ...row.config }));
}

export async function addMediaConfig(config) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not logged in');

  const mediaUrl = await uploadMedia(user.id, config.mediaUrl, config.fileName);
  const sfxUrl = config.sfxUrl ? await uploadMedia(user.id, config.sfxUrl, config.sfxFileName) : '';

  const finalConfig = {
    ...config,
    mediaUrl,
    sfxUrl,
    id: undefined, // will be generated by DB
  };

  const { data, error } = await supabase
    .from('media_configs')
    .insert([{ user_id: user.id, config: finalConfig }])
    .select()
    .single();

  if (error) throw error;
  return { id: data.id, ...data.config };
}

export async function updateMediaConfig(id, updates) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not logged in');

  let mediaUrl = updates.mediaUrl;
  if (mediaUrl && mediaUrl.startsWith('data:')) {
    mediaUrl = await uploadMedia(user.id, mediaUrl, updates.fileName);
  }

  let sfxUrl = updates.sfxUrl;
  if (sfxUrl && sfxUrl.startsWith('data:')) {
    sfxUrl = await uploadMedia(user.id, sfxUrl, updates.sfxFileName);
  }

  const finalUpdates = {
    ...updates,
    mediaUrl: mediaUrl || updates.mediaUrl,
    sfxUrl: sfxUrl !== undefined ? sfxUrl : updates.sfxUrl,
  };

  // Fetch current config block
  const { data: current, error: fetchErr } = await supabase
    .from('media_configs')
    .select('config')
    .eq('id', id)
    .single();

  if (fetchErr) throw fetchErr;

  const newConfig = { ...current.config, ...finalUpdates };

  const { data, error } = await supabase
    .from('media_configs')
    .update({ config: newConfig })
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return { id: data.id, ...data.config };
}

export async function deleteMediaConfig(id) {
  const { error } = await supabase
    .from('media_configs')
    .delete()
    .eq('id', id);

  if (error) throw error;
  return true;
}

export async function getMediaConfigById(id) {
  const { data, error } = await supabase
    .from('media_configs')
    .select('*')
    .eq('id', id)
    .single();

  if (error) return null;
  return { id: data.id, ...data.config };
}

export const ANIMATION_OPTIONS = [
  { value: 'fadeIn', label: 'Fade In' },
  { value: 'pop', label: 'Pop' },
  { value: 'slideUp', label: 'Slide Up' },
  { value: 'slideDown', label: 'Slide Down' },
  { value: 'slideLeft', label: 'Slide Left' },
  { value: 'slideRight', label: 'Slide Right' },
  { value: 'bounce', label: 'Bounce' },
  { value: 'zoomRotate', label: 'Zoom+Rotate' },
  { value: 'flip', label: 'Flip' },
];

export const ANIMATION_OUT_OPTIONS = [
  { value: 'fadeOut', label: 'Fade Out' },
  { value: 'popOut', label: 'Pop' },
  { value: 'slideUpOut', label: 'Slide Up' },
  { value: 'slideDownOut', label: 'Slide Down' },
  { value: 'slideLeftOut', label: 'Slide Left' },
  { value: 'slideRightOut', label: 'Slide Right' },
  { value: 'bounceOut', label: 'Bounce' },
  { value: 'zoomRotateOut', label: 'Zoom+Rotate' },
  { value: 'flipOut', label: 'Flip' },
];
